

// File generated by OpenXava: Thu Jul 21 11:24:20 CEST 2016
// Archivo generado por OpenXava: Thu Jul 21 11:24:20 CEST 2016

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: IssueList		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IIssueList  extends org.openxava.model.IModel {	

	// Properties/Propiedades		

	// References/Referencias 

	// Issue : Reference/Referencia
	
	org.openxava.test.model.IIssue getIssue() throws RemoteException;
	void setIssue(org.openxava.test.model.IIssue newIssue) throws RemoteException;

	// Methods 


}