

// File generated by OpenXava: Mon Jun 12 13:13:08 CEST 2017
// Archivo generado por OpenXava: Mon Jun 12 13:13:08 CEST 2017

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: SellerLevel		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface ISellerLevel  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	public static final String PROPERTY_id = "id"; 	
	String getId() throws RemoteException; 	
	public static final String PROPERTY_description = "description"; 
	String getDescription() throws RemoteException;
	void setDescription(String description) throws RemoteException;		

	// References/Referencias

	// Methods 


}